name: StackHawk Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  stackhawk:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
